version: '3.8'

services:
  longevity-ai:
    build: .
    ports:
      - "8888:8888"  # Jupyter Lab port
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --token='' --allow-root